---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: geerlingguy/ubuntu2004
    box_version: 1.0.2
    memory: 1024
    cpu: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
